version: '3.8'

services:
  postgres:
    container_name: tbca-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: tbca
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
