// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebScrapping.Infrastructure.DataAccess;

#nullable disable

namespace WebScrapping.Infrastructure.Migrations
{
    [DbContext(typeof(WebScrappingDbContext))]
    [Migration("20250208154326_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebScrapping.Domain.Entities.Food", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("WebScrapping.Domain.Entities.FoodComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<string>("FoodCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumValue")
                        .HasColumnType("numeric");

                    b.Property<int?>("NumberOfDataUsed")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValuePer100g")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FoodCode");

                    b.ToTable("FoodComposition");
                });

            modelBuilder.Entity("WebScrapping.Domain.Entities.FoodComposition", b =>
                {
                    b.HasOne("WebScrapping.Domain.Entities.Food", "Food")
                        .WithMany("Compositions")
                        .HasForeignKey("FoodCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("WebScrapping.Domain.Entities.Food", b =>
                {
                    b.Navigation("Compositions");
                });
#pragma warning restore 612, 618
        }
    }
}
